/* Sesotho translations. Keys match the data-i18n attributes in the PHP pages.
   English is the text already in the HTML, so only Sesotho is stored here. */
window.sesotho = {
    /* Navigation and footer */
    'nav.home': 'Lehae',
    'nav.about': 'Ka rona',
    'nav.tours': 'Maeto',
    'nav.cruises': 'Maeto a sekepe nokeng',
    'nav.dome': 'Vredefort Dome',
    'nav.heritage': 'Maeto a lefa',
    'nav.gallery': 'Ditshwantsho',
    'nav.contact': 'Ikopanye le rona',
    'footer.tagline': 'Maeto a tataiswang a nokeng, tlhahong le lefeng Vaal Triangle ho tloha ka 2016.',
    'footer.contact': 'Dintlha tsa puisano',
    'footer.follow': 'Re latele',
    'footer.links': 'Dikgokahano tse molemo',
    'footer.rights': 'Ditokelo tsohle di sirelleditswe.',

    /* Home */
    'home.title': 'Sibolla Vaal',
    'home.intro': 'Maeto a sekepe ha letsatsi le dikela, sekoti sa meteor se setsofadi ho feta bophelo lefatsheng, le dipale tse bopileng Afrika Borwa, kaofela di le hora e le nngwe ho tloha Johannesburg.',
    'home.cta1': 'Sheba maeto a rona',
    'home.cta2': 'Bukisa jwale',
    'home.featured': 'Moo re tla o isa teng',
    'home.featuredText': 'Kgetha ho tse tharo tse tataiswang, e nngwe le e nngwe e etelletswe pele ke motataisi wa lehae ya tsebang Vaal.',
    'home.card1': 'Phomola leetong la sekepe la dihora tse pedi ha letsatsi le dikela, ka dijo tse bobebe, dinonyana le mmino o phelang.',
    'home.card2': 'Tsamaya ka maoto sekoting sa meteor se seholo le se setsofadi ka ho fetisisa lefatsheng, sebaka sa Lefa la Lefatshe sa UNESCO.',
    'home.card3': 'Tsamaya nalaneng ya Sharpeville le Vaal Triangle le moqoqi wa dipale wa lehae.',
    'home.more': 'Bala haholwanyane',
    'home.whyTitle': 'Ke hobaneng o lokela ho etela Vaal?',
    'home.whyText': 'Noka ya Vaal ke e nngwe ya dinoka tse kgolo ka ho fetisisa Afrika Borwa, mme ke sebaka seo batho ba Gauteng ba se ratang mafelong a beke. E fana ka dipapadi tsa metsing, tlhaho, nalane le dijo tse monate sebakeng se le seng.',
    'home.why1': 'Ka tlase ho hora e le nngwe ho tloha Johannesburg',
    'home.why2': 'Bataisi ba lehae ba rutehileng le ba mosa',
    'home.why3': 'Maeto a malapa, dikolo le dihlopha',
    'home.why4': 'Diketswana tse bolokehileng tse nang le dibaki tsa ho phaphamala bakeng sa bohle',
    'home.videoCaption': 'Ponahalo e kgutshwane ya leeto la rona la sekepe ha letsatsi le dikela.',
    'home.stat1': 'baeti ba thabileng',
    'home.stat2': 'maeto a ikgethang',
    'home.stat3': 'tekanyetso e mahareng',
    'home.stat4': 're tataisa ho tloha',
    'home.reviews': 'Seo baeti ba rona ba se buang',
    'home.review1': '"Leeto la sekepe ha letsatsi le dikela e bile karolo e monate ka ho fetisisa ya leeto la rona. Motataisi o ne a tseba nonyana e nngwe le e nngwe ka lebitso!"',
    'home.review2': '"Ke ne ke sa tsebe hore sekoti sa meteor se haufi hakana le hae. Leeto la Vredefort le ne le makatsa."',
    'home.review3': '"Leeto la lefa le ne le ama pelo mme le hlalositswe hantle haholo. Moafrika Borwa e mong le e mong o lokela ho ya."',
    'home.ctaTitle': 'Etela Vaal le rona',
    'home.ctaText': 'Bukisa leeto bakeng sa hao, lelapa la hao kapa sehlopha sa sekolo sa hao mme o bone noka kamoo batho ba lehae ba e bonang kateng.',
    'home.eyebrow': 'Noka ya Vaal',
    'home.beautyTitle': 'Botle bo ikgethang ba Vaal Triangle',
    'home.mapCard': 'Re bone mmapeng',
    'home.weatherCard': 'Matsatsi a chesang a lehlabula',
    'home.ratingCard': 'E lekantswe ke baeti ba thabileng ba fetang 10 000',
    'home.sharpeville': 'Sharpeville',
    'home.card4': 'Toropo e pela noka e nang le dirapa tse tala, direstorente le dibaka tse ntle tsa pikiniki.',
    'home.priceTitle': 'Theko e molemo ka ho fetisisa bakeng sa letsatsi nokeng',
    'home.priceText': 'Maeto a sekepe a qala ho R350 bakeng sa motho e moholo mme bana ba ka tlase ho dilemo tse 12 ba lefa hoo e ka bang halofo. Dihlopha tsa batho ba 15 kapa ho feta di fumana theolelo ya 10%.',
    'home.seePrices': 'Sheba ditheko',

    /* About */
    'about.title': 'Ka Vaal Adventures',
    'about.intro': 'Khampani ya maeto ya lehae e tsamaiswang ke lelapa, e arolelanang tse molemo ka ho fetisisa tsa Vaal Triangle.',
    'about.storyTitle': 'Pale ya rona',
    'about.story1': 'Vaal Adventures e qadile ka 2016 ka sekepe se le seng se senyenyane le lerato le leholo bakeng sa noka. Mothehi wa rona o holetse Vanderbijlpark mme o ne a batla hore baeti ba bone Vaal kamoo batho ba lehae ba e bonang kateng.',
    'about.story2': 'Kajeno re tsamaisa maeto a sekepe nokeng, maeto a letsatsi ho ya Vredefort Dome le maeto a lefa Sharpeville. Re sebetsa le bataisi, direschorente le barekisi ba mesebetsi ya matsoho ba lehae hore tjhelete ya bohahlaodi e dule setjhabeng sa rona.',
    'about.caption': 'Noka ya Vaal haufi le Vanderbijlpark.',
    'about.valuesTitle': 'Seo re se emelang',
    'about.v1': 'Polokeho pele',
    'about.v1Text': 'Diketswana tsohle di a hlahlobjwa mme moeti e mong le e mong o fumana baki ya ho phaphamala. Bakhanni ba rona ba diketswana ba na le dilaesense tse nepahetseng.',
    'about.v2': 'Ho hlompha tlhaho',
    'about.v2Text': 'Re boloka dihlopha di le nyenyane, re kgutlisetsa ditshila tsohle hae mme re tshehetsa matsatsi a ho hlwekisa noka.',
    'about.v3': 'Setjhaba sa lehae',
    'about.v3Text': 'Bataisi ba rona ba tswa Vaal Triangle mme re reka dikgwebong tsa lehae.',
    'about.teamTitle': 'Kopana le sehlopha',
    'about.teamCaption': 'Bataisi ba rona le seo ba se tsebang hantle',
    'about.thName': 'Lebitso',
    'about.thRole': 'Mosebetsi',
    'about.thLang': 'Dipuo',
    'about.r1': 'Mothehi le mokhanni wa sekepe',
    'about.r2': 'Motataisi wa lefa',
    'about.r3': 'Motataisi wa jeoloji le ho tsamaya ka maoto',
    'about.r4': 'Dipukisetso le tlhokomelo ya bareki',
    'about.partnersTitle': 'Ithute haholwanyane ka sebaka sena',

    /* Tours */
    'tours.title': 'Maeto a rona',
    'tours.intro': 'Mekgwa e meraro ya ho natefelwa ke Vaal: metsing, maralleng le nalaneng ya yona.',
    'tours.from': 'Ho tloha ho',
    'tours.twoHours': 'Dihora tse 2',
    'tours.threeHours': 'Dihora tse 3',
    'tours.fullDay': 'Letsatsi lohle (dihora tse 8)',
    'tours.max30': 'Ho fihla ho baeti ba 30',
    'tours.moderate': 'Ho tsamaya ka maoto ho mahareng',
    'tours.walking': 'Leeto la ho tsamaya ka maoto',
    'tours.included': 'Se kenyeleditsweng',
    'tours.cruiseText': 'Palama sekepe sa rona se kwahetsweng boemelong ba Riverside mme o tsamaye pela dihlekehleke, difate tsa meluluwe le dilodge tse pela noka. Sheba ntsu ya ditlhapi le dinonyana tse ding ha letsatsi le dikela hodima metsi.',
    'tours.c1': 'Seno sa kamohelo le poleiti ya dijo tse bobebe',
    'tours.c2': 'Dibaki tsa ho phaphamala le tlhahiso ya polokeho',
    'tours.c3': 'Tlhaloso ya motataisi ka dinonyana le nalane',
    'tours.c4': 'Mmino o phelang ka Moqebelo',
    'tours.domeText': 'Dilemong tse ka bang dibilione tse pedi tse fetileng, lefika le leholo le tswang sebakeng le ile la otla lefatshe haufi le toropo ya Parys. Sekoti seo le se siileng ke sona se setsofadi le se seholo ka ho fetisisa se bonahalang Lefatsheng. Motataisi wa rona wa jeoloji o tla o bontsha mafika le maralla a phetang pale ena.',
    'tours.d1': 'Dipalangwang tsa ho ya le ho kgutla ho tloha Vanderbijlpark',
    'tours.d2': 'Ho tsamaya ka maoto le motataisi wa jeoloji',
    'tours.d3': 'Dijo tsa motshehare reschorenteng e pela noka',
    'tours.d4': 'Ditefello tsa ho kena',
    'tours.unesco': 'Bala ka Vredefort Dome webosaeteng ya UNESCO',
    'tours.heritageText': 'Ka la 21 Hlakubele 1960 mapolesa a ile a thunya batho ba neng ba ipelaetsa kgahlanong le melao ya dipase Sharpeville. Kajeno Afrika Borwa e hopola letsatsi lena e le Letsatsi la Ditokelo tsa Botho. Motataisi wa rona wa lefa o o isa sefikeng sa sehopotso le musiamong mme o arolelana dipale tsa setjhaba.',
    'tours.h1': 'Ketelo sehopotsong sa Sharpeville le setsing sa dipontsho',
    'tours.h2': 'Motataisi wa lehae ya tswang setjhabeng',
    'tours.h3': 'Dijo tsa setso tsa motshehare reschorenteng ya lehae',
    'tours.sahistory': 'Ithute haholwanyane ho South African History Online',
    'tours.tableCaption': 'Ditheko le dinako tsa maeto (2026)',
    'tours.thTour': 'Leeto',
    'tours.thDays': 'Matsatsi',
    'tours.thTime': 'Ho tloha',
    'tours.thAdult': 'Motho e moholo',
    'tours.thChild': 'Ngwana (ka tlase ho dilemo tse 12)',
    'tours.daysCruise': 'Laboraro ho isa Sontaha',
    'tours.daysDome': 'Moqebelo',
    'tours.daysHeritage': 'Labobedi ho isa Moqebelo',
    'tours.calcTitle': 'Sebali sa theko',
    'tours.adults': 'Batho ba baholo',
    'tours.children': 'Bana',
    'tours.total': 'Kakaretso:',

    /* Gallery */
    'gallery.title': 'Ditshwantsho le divideo',
    'gallery.intro': 'Dinako tse monate tsa maeto a rona. Tobetsa setshwantsho ho se bona se seholwanyane.',
    'gallery.photos': 'Ditshwantsho',
    'gallery.videos': 'Divideo',
    'gallery.video1': 'Leeto la sekepe ha letsatsi le dikela',
    'gallery.video2': 'Leeto la letsatsi ho ya Vredefort Dome',

    /* Contact */
    'contact.title': 'Ikopanye le rona mme o bukise leeto',
    'contact.intro': 'Re romele kopo ya pukisetso mme re tla netefatsa sebaka sa hao nakong ya letsatsi le le leng la mosebetsi.',
    'contact.formTitle': 'Kopo ya pukisetso',
    'contact.name': 'Lebitso le feletseng',
    'contact.email': 'Imeile',
    'contact.phone': 'Nomoro ya mohala',
    'contact.choose': 'Kgetha leeto',
    'contact.date': 'Letsatsi',
    'contact.message': 'Molaetsa (ha o a tlameha)',
    'contact.send': 'Romela kopo',
    'contact.findUs': 'Moo re fumanehang',
    'contact.hours': 'Dihora tsa ofisi',
    'contact.weekdays': 'Mantaha ho isa Labohlano',
    'contact.saturday': 'Moqebelo',
    'contact.sunday': 'Sontaha le matsatsi a phomolo a setjhaba',
    'contact.closed': 'E kwetswe (maeto a ntse a tsamaya)',
    'contact.directions': 'Fumana ditsela ho Google Maps',
    'contact.faqTitle': 'Dipotso tse botswang kgafetsa',
    'contact.q1': 'Ke tlise eng?',
    'contact.a1': 'Tlisa katiba, setlolo sa letsatsi, metsi le dieta tse phutholohileng. Bakeng sa leeto la sekepe, tlisa baki e bobebe bakeng sa mantsiboya.',
    'contact.q2': 'Na nka hlakola pukisetso ya ka?',
    'contact.a2': 'E. Hlakola bonyane dihora tse 48 pele ho leeto mme o tla kgutlisetswa tjhelete yohle.',
    'contact.q3': 'Na le fana ka theolelo ho dikolo le dihlopha?',
    'contact.a3': 'E. Dihlopha tsa batho ba 15 kapa ho feta di fumana theolelo ya 10%. Ikopanye le rona bakeng sa diphutheloana tsa maeto a dikolo.'
};
